steps:
  # 1. Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_SERVICE}:$COMMIT_SHA', './backend']
    id: 'build-backend'

  # 2. Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_SERVICE}:$COMMIT_SHA']
    id: 'push-backend'
    waitFor: ['build-backend']

  # 3. Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_API_SERVICE}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_SERVICE}:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--min-instances=0'
      - '--max-instances=1'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--concurrency=20'
      - '--set-env-vars=ROUTING_PROVIDER=mock'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # 4. Build Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:$COMMIT_SHA', './frontend']
    id: 'build-frontend'
    waitFor: ['deploy-backend']

  # 5. Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:$COMMIT_SHA']
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # 6. Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_WEB_SERVICE}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--min-instances=0'
      - '--max-instances=1'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--set-env-vars=API_BASE_URL=https://carless-life-api-788259830737.asia-northeast1.run.app'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

substitutions:
  _REGION: 'asia-northeast1'
  _AR_REPO: 'carless-life'
  _API_SERVICE: 'carless-life-api'
  _WEB_SERVICE: 'carless-life-web'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_SERVICE}:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:$COMMIT_SHA'
